- hosts: nodejs_servers
  gather_facts: true
  vars_files:
    - vars/main.yml
  vars:
    NODEJS_VERSION: "v20.14.0"
    node_version_path: "{{ ansible_env.HOME }}/.nvm/versions/node/{{ NODEJS_VERSION }}/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ node_version_path }}"
  tasks:
    - name: Update apt repo and cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
      ignore_errors: yes

    - name: "Instaling packages"
      become: yes
      apt:
        name:
          - curl
          - git
        update_cache: yes
      ignore_errors: yes
      
    - name: "Run NVM installer script"
      shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
      args:
        executable: /bin/bash
        creates: "$HOME/.nvm/nvm.sh"
 
    - name: Set execute permission for nvm.sh script
      ansible.builtin.file:
        path: "$HOME/.nvm/nvm.sh"
        mode: "+x"

    - name: Source nvm in ~/.{{ item }}
      lineinfile:
        dest: ~/.{{ item }}
        line: "source ~/.nvm/nvm.sh"
        create: yes
      tags: nvm
      with_items:
        - bashrc
        - profile

    - name: "Checking if NVM was installed correctly"
      shell: "source ~/.nvm/nvm.sh && nvm install {{NODEJS_VERSION}} && nvm alias default {{NODEJS_VERSION}} && nvm use default" 
      args:
        executable: /bin/bash
      register: output
      ignore_errors: true

    - name: Checking node version
      shell: "node -v"
      register: version

    - debug:
        msg: "{{ version.stdout }}"

    