- hosts: data_app
  become: yes
  vars_files:
    - vars/main.yml
  vars: 
    username: "{{ mysql_users[0].name }}"
    password: "{{lookup('env', 'DB_PASSWORD')}}"
    db_name: "{{mysql_databases[0].name}}"
  roles:
    - { role: geerlingguy.mysql }
  post_tasks:
  - name: "Check if Mysql Script exists on remote machine"
    stat:
      path: "/home/{{ ansible_user }}/test.sql"
    register: mysql_script

  - name: "Copy Mysql Script From local machine to remote machine"
    copy:
      src: "test.sql"
      dest: "/home/{{ ansible_user }}/test.sql"
      mode: "0755"
    when: mysql_script.stat.exists == false

  - name: Allow 3306/tcp through UFW
    ufw:
      rule: allow
      port: '3306'
      proto: tcp

  - name: Creating Tables in DB
    community.mysql.mysql_db:
      login_user: "{{username}}"
      login_password: "{{password}}"
      name: "{{db_name}}"
      state: import
      target: /home/{{ansible_user}}/test.sql
    register: output

  - name: debuging previous step
    debug: var=output
    tags:
      - test_table
