mysql_root_username: root
mysql_root_password: root
mysql_root_password_update: false
mysql_enabled_on_startup: true
mysql_databases:
  - name: test
    encoding: latin1
    collation: latin1_general_ci
mysql_users: 
  - name: rafiktaamma 
    password: "{{lookup('env', 'mysql_password')}}" # Password is retrieved from the environement variable 
    host: "localhost"
    priv: "*.*:ALL"
  - name: rafiktaamma 
    password: "{{lookup('env', 'mysql_password')}}" # Password is retrieved from the environement variable 
    host: "%"
    priv: "*.*:ALL"
db_port: 3306
NODEJS_VERSION: "v20.14.0"
business_app_port: 8080
web_app_port: 3000